version: '3.8'

services:
  api-gateway:
    container_name: api_service
    build: ./
    ports:
      - "50001:50001"
    networks:
      - global-network
 
# Docker Networks
networks:
  global-network:
    external: true 

